spring.application.name=hoangkiencoffee

spring.datasource.url=jdbc:mysql://localhost:3306/keycoffee?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=230104
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=20221608@eaut.edu.vn
spring.mail.password=fani ruby dnui fqho
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
